
[build]
  
  base = "project/"

  
  publish = "build-output/"

  command = "echo 'default context'"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

